openapi: 3.0.3
info:
  title: UniMed API
  description: UniMed API
  version: 1.0.0
servers:
  - url: https://dev-api.unimed.com/api/v1
externalDocs:
  url: https://wiki.andersenlab.com/display/UNM/1.+MVP
  description: UniMed Wiki

paths:
  /visibility:
    get:
      summary: visibilityGet
      description: visibilityGet
      operationId: visibilityGet
      responses:
        '200':
          description: visibilityGet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisibilityObject'
    post:
      summary: visibilityPost
      description: visibilityPost
      operationId: visibilityPost
      requestBody:
        description: visibilityPost
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VisibilityObject'
      responses:
        '200':
          description: visibilityPost
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisibilityObject'
components:
  schemas:
    VisibilityObject:
      type: object
      properties:
        onlyForRequest:
          type: string
          writeOnly: true
        onlyForResponse:
          type: string
          readOnly: true
        forBoth:
          type: string
        nullableField:
          type: string
          nullable: true
        requiredField:
          type: string
        nullablePatternField:
          type: string
          nullable: true
          pattern: '^[a-zA-Z0-9]+$'
          x-pattern-message: 'Only letters and numbers are allowed'
          minLength: 1
          maxLength: 20
        dateField:
          type: string
          format: date
          example: 2020-01-01
          description: Date
        dateTimeField:
          type: string
          format: date-time
          example: 2020-01-01T00:00:00Z
          description: Date time
        deprecatedField:
          type: string
          deprecated: true

      required:
        - requiredField

